# Generated by Django 5.2.8 on 2025-12-07 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.FloatField(verbose_name='Coordenada X')),
                ('y_coord', models.FloatField(verbose_name='Coordenada Y')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isReturn', models.BooleanField()),
                ('distance', models.FloatField()),
                ('time', models.FloatField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routecalc.line')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_of', to='routecalc.point')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orig_of', to='routecalc.point')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routecalc.route')),
            ],
        ),
    ]
