# Generated by Django 5.2.8 on 2025-11-27 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routecalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='direction',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='routecalc.line'),
        ),
    ]
