# Generated by Django 5.2.8 on 2025-12-07 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routecalc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest_of', to='routecalc.point'),
        ),
    ]
