# Generated by Django 5.2.8 on 2025-12-08 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routecalc', '0002_alter_step_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='step',
            name='origin',
        ),
        migrations.AddField(
            model_name='step',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='routecalc.step'),
        ),
        migrations.AddField(
            model_name='step',
            name='point',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='routecalc.point'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='routecalc.line'),
        ),
    ]
