# Generated by Django 5.2.8 on 2025-11-27 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routecalc', '0002_route_direction_alter_route_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='line',
            field=models.ForeignKey(default='100', on_delete=django.db.models.deletion.CASCADE, to='routecalc.line'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='path',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routecalc.point'),
        ),
        migrations.AlterField(
            model_name='path',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='routecalc.point'),
        ),
    ]
