# Generated by Django 5.2.8 on 2025-12-08 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routecalc', '0003_remove_step_destination_remove_step_origin_step_next_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='first',
            field=models.ForeignKey(default=86, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='routecalc.step'),
            preserve_default=False,
        ),
    ]
