# Generated by Django 5.2.8 on 2025-12-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routecalc', '0004_route_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=10),
            preserve_default=False,
        ),
    ]
